[package]
name = "ed-logs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-macro = "0.2.0"
once_cell = "1.19.0"
thiserror = "1.0.58"
regex = "1.10.4"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

[features]
default = ["strict"]
strict = []
